{
  "candidate": "CVE-2005-3195",
  "description": "** REJECT **  DO NOT USE THIS CANDIDATE NUMBER.  ConsultIDs: CVE-2005-3178. Reason: this candidate is a duplicate of CVE-2005-3178; the duplicate arose from a pre-candidate that was not deleted during the editing phase. Notes: All CVE users should reference CVE-2005-3178 instead of this candidate.  All references and descriptions in this candidate have been removed to prevent accidental usage.",
  "priority": "untriaged",
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2005-3195"
  ],
  "public_date": "2005-10-14 10:02:00 UTC",
  "packages": {
    "dapper": {
      "xli": {
        "name": "xli",
        "status": "not-affected"
      },
      "xloadimage": {
        "name": "xloadimage",
        "status": "not-affected"
      }
    },
    "devel": {
      "xli": {
        "name": "xli",
        "status": "not-affected"
      },
      "xloadimage": {
        "name": "xloadimage",
        "status": "not-affected"
      }
    },
    "edgy": {
      "xli": {
        "name": "xli",
        "status": "not-affected"
      },
      "xloadimage": {
        "name": "xloadimage",
        "status": "not-affected"
      }
    },
    "feisty": {
      "xli": {
        "name": "xli",
        "status": "not-affected"
      },
      "xloadimage": {
        "name": "xloadimage",
        "status": "not-affected"
      }
    },
    "upstream": {
      "xli": {
        "name": "xli",
        "status": "needs-triage"
      },
      "xloadimage": {
        "name": "xloadimage",
        "status": "needs-triage"
      }
    }
  }
}
