{
	"candidate": "CVE-2014-0481",
	"description": "The default configuration for the file upload handling system in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 uses a sequential file name generation process when a file with a conflicting name is uploaded, which allows remote attackers to cause a denial of service (CPU consumption) by unloading a multiple files with the same name.",
	"priority": "low",
	"references": [
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0481",
		"https://www.djangoproject.com/weblog/2014/aug/20/security/",
		"https://ubuntu.com/security/notices/USN-2347-1"
	],
	"assigned_to": "mdeslaur",
	"discovered_by": "David Wilson",
	"public_date": "2014-08-26 14:55:00 UTC",
	"public_date_at_usn": "2014-08-26",
	"packages": {
		"devel": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected",
				"note": "1.6.6-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/30042d475bf084c6723c6217a21598d9247a9c41 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/dd0c3f4ee1a30c1a1e6055061c6ba6e58c6b54d1 (1.6)"
					}
				]
			}
		},
		"lucid": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.1.1-2ubuntu1.13",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/30042d475bf084c6723c6217a21598d9247a9c41 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/dd0c3f4ee1a30c1a1e6055061c6ba6e58c6b54d1 (1.6)"
					}
				]
			}
		},
		"precise": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.3.1-4ubuntu1.12",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/30042d475bf084c6723c6217a21598d9247a9c41 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/dd0c3f4ee1a30c1a1e6055061c6ba6e58c6b54d1 (1.6)"
					}
				]
			}
		},
		"trusty": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.1-2ubuntu0.4",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/30042d475bf084c6723c6217a21598d9247a9c41 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/dd0c3f4ee1a30c1a1e6055061c6ba6e58c6b54d1 (1.6)"
					}
				]
			}
		},
		"trusty/esm": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.1-2ubuntu0.4",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/30042d475bf084c6723c6217a21598d9247a9c41 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/dd0c3f4ee1a30c1a1e6055061c6ba6e58c6b54d1 (1.6)"
					}
				]
			}
		},
		"upstream": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.6-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/30042d475bf084c6723c6217a21598d9247a9c41 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/dd0c3f4ee1a30c1a1e6055061c6ba6e58c6b54d1 (1.6)"
					}
				]
			}
		}
	}
}
