{
	"candidate": "CVE-2024-27351",
	"description": "In Django 3.2 before 3.2.25, 4.2 before 4.2.11, and 5.0 before 5.0.3, the django.utils.text.Truncator.words() method (with html=True) and the truncatewords_html template filter are subject to a potential regular expression denial-of-service attack via a crafted string. NOTE: this issue exists because of an incomplete fix for CVE-2019-14232 and CVE-2023-43665.",
	"priority": "medium",
	"references": [
		"https://www.djangoproject.com/weblog/2024/mar/04/security-releases/",
		"https://ubuntu.com/security/notices/USN-6674-1",
		"https://ubuntu.com/security/notices/USN-6674-2",
		"https://www.cve.org/CVERecord?id=CVE-2024-27351"
	],
	"discovered_by": "Seokchan Yoon",
	"public_date": "2024-03-15 20:15:00 UTC",
	"public_date_at_usn": "2024-03-04 09:00:00 UTC",
	"crd": "2024-03-04 09:00:00 UTC",
	"packages": {
		"bionic": {
			"python-django": {
				"name": "python-django",
				"status": "ignored",
				"note": "end of standard support"
			}
		},
		"devel": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "3:4.2.11-1"
			}
		},
		"esm-infra-legacy/trusty": {
			"python-django": {
				"name": "python-django",
				"status": "needs-triage"
			}
		},
		"esm-infra/bionic": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1:1.11.11-1ubuntu1.21+esm4"
			}
		},
		"esm-infra/xenial": {
			"python-django": {
				"name": "python-django",
				"status": "needs-triage"
			}
		},
		"focal": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "2:2.2.12-1ubuntu0.22"
			}
		},
		"jammy": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "2:3.2.12-2ubuntu1.11"
			}
		},
		"mantic": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "3:4.2.4-1ubuntu2.2"
			}
		},
		"noble": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "3:4.2.11-1"
			}
		},
		"trusty": {
			"python-django": {
				"name": "python-django",
				"status": "ignored",
				"note": "end of standard support"
			}
		},
		"trusty/esm": {
			"python-django": {
				"name": "python-django",
				"status": "needs-triage"
			}
		},
		"upstream": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "3.2.25,4.2.11,5.0.3"
			}
		},
		"xenial": {
			"python-django": {
				"name": "python-django",
				"status": "ignored",
				"note": "end of standard support"
			}
		}
	}
}
