{
	"candidate": "CVE-2019-6786",
	"description": "An issue was discovered in GitLab Community and Enterprise Edition before 11.5.8, 11.6.x before 11.6.6, and 11.7.x before 11.7.1. It has Incorrect Access Control (issue 1 of 3). The contents of an LFS object can be accessed by an unauthorized user, if the file size and OID are known.",
	"notes": {
		"msalvatore": "Affects GitLab 8.16 and later"
	},
	"priority": "untriaged",
	"cvss": {
		"nvd": " CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N [6.5 MEDIUM]"
	},
	"references": [
		"https://about.gitlab.com/2019/01/31/security-release-gitlab-11-dot-7-dot-3-released/",
		"https://www.cve.org/CVERecord?id=CVE-2019-6786"
	],
	"public_date": "2019-09-09 20:15:00 UTC",
	"packages": {
		"bionic": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"cosmic": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"devel": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"disco": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"eoan": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"esm-apps/xenial": {
			"gitlab": {
				"name": "gitlab",
				"status": "not-affected",
				"note": "code not present"
			}
		},
		"esm-infra-legacy/trusty": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"precise/esm": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"trusty": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"trusty/esm": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"upstream": {
			"gitlab": {
				"name": "gitlab",
				"status": "needs-triage"
			}
		},
		"xenial": {
			"gitlab": {
				"name": "gitlab",
				"status": "not-affected",
				"note": "code not present"
			}
		}
	}
}
