{
	"candidate": "CVE-2015-0221",
	"description": "The django.views.static.serve view in Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 reads files an entire line at a time, which allows remote attackers to cause a denial of service (memory consumption) via a long line in a file.",
	"priority": "medium",
	"references": [
		"https://www.djangoproject.com/weblog/2015/jan/13/security/",
		"https://ubuntu.com/security/notices/USN-2469-1",
		"https://www.cve.org/CVERecord?id=CVE-2015-0221"
	],
	"assigned_to": "mdeslaur",
	"discovered_by": "Alex Gaynor",
	"public_date": "2015-01-16 16:59:00 UTC",
	"public_date_at_usn": "2015-01-13",
	"packages": {
		"devel": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.6-1ubuntu3"
			}
		},
		"esm-infra-legacy/trusty": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected",
				"note": "1.6.1-2ubuntu0.6"
			}
		},
		"lucid": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.1.1-2ubuntu1.14"
			}
		},
		"precise": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.3.1-4ubuntu1.13"
			}
		},
		"trusty": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.1-2ubuntu0.6"
			}
		},
		"trusty/esm": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected",
				"note": "1.6.1-2ubuntu0.6"
			}
		},
		"upstream": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.10"
			}
		},
		"utopic": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.6-1ubuntu2.1"
			}
		}
	}
}
