{
	"candidate": "CVE-2016-2048",
	"description": "Django 1.9.x before 1.9.2, when ModelAdmin.save_as is set to True, allows remote authenticated users to bypass intended access restrictions and create ModelAdmin objects via the \"Save as New\" option when editing objects and leveraging the \"change\" permission.",
	"notes": {
		"mdeslaur": "1.9.x only"
	},
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.0/AV:N/AC:L/PR:H/UI:N/S:U/C:L/I:H/A:N [5.5 MEDIUM]"
	},
	"bugs": [
		"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813448"
	],
	"references": [
		"https://www.djangoproject.com/weblog/2016/feb/01/releases-192-and-189/",
		"https://www.cve.org/CVERecord?id=CVE-2016-2048"
	],
	"public_date": "2016-02-08 19:59:00 UTC",
	"packages": {
		"devel": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected",
				"note": "1.8.7-1ubuntu1"
			}
		},
		"esm-infra-legacy/trusty": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected"
			}
		},
		"precise": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected"
			}
		},
		"trusty": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected"
			}
		},
		"trusty/esm": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected"
			}
		},
		"upstream": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.9.2-1"
			}
		},
		"vivid": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected"
			}
		},
		"vivid/stable-phone-overlay": {
			"python-django": {
				"name": "python-django",
				"status": "DNE"
			}
		},
		"vivid/ubuntu-core": {
			"python-django": {
				"name": "python-django",
				"status": "DNE"
			}
		},
		"wily": {
			"python-django": {
				"name": "python-django",
				"status": "not-affected"
			}
		}
	}
}
