{
  "candidate": "CVE-2021-28378",
  "description": "Gitea 1.12.x and 1.13.x before 1.13.4 allows XSS via certain issue data in some situations.",
  "priority": "medium",
  "cvss": {
    "nvd": " CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N [5.4 MEDIUM]"
  },
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28378",
    "https://blog.gitea.io/2021/03/gitea-1.13.4-is-released/",
    "https://github.com/go-gitea/gitea/pull/14898"
  ],
  "public_date": "2021-03-15 06:15:00 UTC",
  "packages": {
    "bionic": {
      "gitea": {
        "name": "gitea",
        "status": "DNE"
      }
    },
    "devel": {
      "gitea": {
        "name": "gitea",
        "status": "DNE"
      }
    },
    "focal": {
      "gitea": {
        "name": "gitea",
        "status": "DNE"
      }
    },
    "groovy": {
      "gitea": {
        "name": "gitea",
        "status": "DNE"
      }
    },
    "precise/esm": {
      "gitea": {
        "name": "gitea",
        "status": "DNE"
      }
    },
    "trusty": {
      "gitea": {
        "name": "gitea",
        "status": "ignored",
        "note": "end of standard support"
      }
    },
    "trusty/esm": {
      "gitea": {
        "name": "gitea",
        "status": "DNE"
      }
    },
    "upstream": {
      "gitea": {
        "name": "gitea",
        "status": "needs-triage"
      }
    },
    "xenial": {
      "gitea": {
        "name": "gitea",
        "status": "DNE"
      }
    }
  }
}
