{
  "candidate": "CVE-2008-1679",
  "description": "Multiple integer overflows in imageop.c in Python before 2.5.3 allow context-dependent attackers to cause a denial of service (crash) and possibly execute arbitrary code via crafted images that trigger heap-based buffer overflows.  NOTE: this issue is due to an incomplete fix for CVE-2007-4965.",
  "priority": "medium",
  "bugs": [
    "https://bugs.launchpad.net/ubuntu/+source/python2.4/+bug/227246"
  ],
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-1679",
    "https://ubuntu.com/security/notices/USN-632-1"
  ],
  "assigned_to": "kees",
  "public_date": "2008-04-22 04:41:00 UTC",
  "packages": {
    "dapper": {
      "python2.4": {
        "name": "python2.4",
        "status": "released",
        "note": "2.4.3-0ubuntu6.2",
        "patches": [
          {
            "source": "vendor",
            "text": "http://www.debian.org/security/2008/dsa-1551"
          }
        ]
      },
      "python2.5": {
        "name": "python2.5",
        "status": "DNE"
      }
    },
    "devel": {
      "python2.4": {
        "name": "python2.4",
        "status": "not-affected",
        "patches": [
          {
            "source": "vendor",
            "text": "http://www.debian.org/security/2008/dsa-1551"
          }
        ]
      },
      "python2.5": {
        "name": "python2.5",
        "status": "not-affected"
      }
    },
    "feisty": {
      "python2.4": {
        "name": "python2.4",
        "status": "released",
        "note": "2.4.4-2ubuntu7.2",
        "patches": [
          {
            "source": "vendor",
            "text": "http://www.debian.org/security/2008/dsa-1551"
          }
        ]
      },
      "python2.5": {
        "name": "python2.5",
        "status": "released",
        "note": "2.5.1-0ubuntu1.2"
      }
    },
    "gutsy": {
      "python2.4": {
        "name": "python2.4",
        "status": "released",
        "note": "2.4.4-6ubuntu4.2",
        "patches": [
          {
            "source": "vendor",
            "text": "http://www.debian.org/security/2008/dsa-1551"
          }
        ]
      },
      "python2.5": {
        "name": "python2.5",
        "status": "released",
        "note": "2.5.1-5ubuntu5.2"
      }
    },
    "hardy": {
      "python2.4": {
        "name": "python2.4",
        "status": "not-affected",
        "patches": [
          {
            "source": "vendor",
            "text": "http://www.debian.org/security/2008/dsa-1551"
          }
        ]
      },
      "python2.5": {
        "name": "python2.5",
        "status": "not-affected"
      }
    },
    "upstream": {
      "python2.4": {
        "name": "python2.4",
        "status": "needs-triage",
        "patches": [
          {
            "source": "vendor",
            "text": "http://www.debian.org/security/2008/dsa-1551"
          }
        ]
      },
      "python2.5": {
        "name": "python2.5",
        "status": "needs-triage"
      }
    }
  }
}
