{
	"candidate": "CVE-2013-1665",
	"description": "The XML libraries for Python 3.4, 3.3, 3.2, 3.1, 2.7, and 2.6, as used in OpenStack Keystone Essex and Folsom, Django, and possibly other products allow remote attackers to read arbitrary files via an XML external entity declaration in conjunction with an entity reference, aka an XML External Entity (XXE) attack.",
	"notes": {
		"jdstrand": "Keystone on 11.10 is a pre-release version and unusable with other components such as nova and horizon"
	},
	"priority": "medium",
	"bugs": [
		"https://bugs.launchpad.net/keystone/+bug/1100279",
		"https://bugs.launchpad.net/bugs/1130445"
	],
	"references": [
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-1665",
		"https://www.djangoproject.com/weblog/2013/feb/19/security/",
		"https://ubuntu.com/security/notices/USN-1730-1",
		"https://ubuntu.com/security/notices/USN-1757-1"
	],
	"discovered_by": "Jonathan Murray",
	"public_date": "2013-04-03 00:55:00 UTC",
	"public_date_at_usn": "2013-02-19",
	"packages": {
		"devel": {
			"keystone": {
				"name": "keystone",
				"status": "not-affected",
				"note": "2013.1.g3-0ubuntu1"
			},
			"python-django": {
				"name": "python-django",
				"status": "not-affected",
				"note": "1.4.5-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112 (1.3)"
					},
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2013/dsa-2634"
					}
				]
			}
		},
		"hardy": {
			"keystone": {
				"name": "keystone",
				"status": "DNE"
			},
			"python-django": {
				"name": "python-django",
				"status": "ignored",
				"note": "end of life",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112 (1.3)"
					},
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2013/dsa-2634"
					}
				]
			}
		},
		"lucid": {
			"keystone": {
				"name": "keystone",
				"status": "DNE"
			},
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.1.1-2ubuntu1.8",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112 (1.3)"
					},
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2013/dsa-2634"
					}
				]
			}
		},
		"oneiric": {
			"keystone": {
				"name": "keystone",
				"status": "ignored"
			},
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.3-2ubuntu1.6",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112 (1.3)"
					},
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2013/dsa-2634"
					}
				]
			}
		},
		"precise": {
			"keystone": {
				"name": "keystone",
				"status": "released",
				"note": "2012.1+stable~20120824-a16a0ab9-0ubuntu2.5"
			},
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.3.1-4ubuntu1.6",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112 (1.3)"
					},
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2013/dsa-2634"
					}
				]
			}
		},
		"quantal": {
			"keystone": {
				"name": "keystone",
				"status": "released",
				"note": "2012.2.1-0ubuntu1.2"
			},
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.4.1-2ubuntu0.3",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112 (1.3)"
					},
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2013/dsa-2634"
					}
				]
			}
		},
		"upstream": {
			"keystone": {
				"name": "keystone",
				"status": "pending",
				"note": "2013.1~g3"
			},
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.4.5-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/1c60d07ba23e0350351c278ad28d0bd5aa410b40 (1.4)"
					},
					{
						"source": "upstream",
						"text": "https://github.com/django/django/commit/d19a27066b2247102e65412aa66917aff0091112 (1.3)"
					},
					{
						"source": "vendor",
						"text": "http://www.debian.org/security/2013/dsa-2634"
					}
				]
			}
		}
	}
}
